from glob import glob
import random
from typing import KeysView
from bs4 import BeautifulSoup
from PIL import Image
import os
import csv

'''
Img format should be First_Last.*
'''

imgDir = glob("../assets/images/people/*")

prefix = os.getcwd()[0:-5]
    
quotes = dict()
with open('../assets/text/sd.csv', mode='r') as inp:
    reader = csv.reader(inp)
    quotes = {rows[1]:rows[2] for rows in reader}

html = BeautifulSoup("<!--Autogenerated HTML--><div class='container card-deck' style='margin:auto;'></div>", 'html.parser')
keys =list(quotes.keys())
random.shuffle(keys)
for i in keys:
    checkImg = "../assets/images/people/" + i
    possibles = [checkImg + i for i in [".png", ".jpg", ".jpeg"]]
    
    imgPath = "../assets/images/people/nopic.png"#"https://www.jumprobotics.org/assets/images/people/nopic.png"
    for j in possibles:
        if os.path.exists(prefix+j[3:]):
            imgPath = j#"https://www.jumprobotics.org"+j[2:]
    
    print(imgPath)
    first, last = i.split("_")
    flip = html.new_tag('div')
    flip['class'] = "flip-card"

    inner = html.new_tag('div')
    inner['class'] = "flip-card-inner"
        
    front = html.new_tag('div')
    front['class'] = "flip-card-front"
        
    img = html.new_tag('img')
    img['class'] = 's'
    img['src'] = imgPath
    front.append(img)
        
    back = html.new_tag('div')
    back['class'] = "flip-card-back"
        
    name = html.new_tag("h1")
    name.append(first + " " + last)
    name['id'] = first+"_"+last
        
    quote = html.new_tag("p")
    
    qText = quotes.get(first+"_"+last)
    if qText=="":
        qText = "Great at coming up with taglines"
    quote.append(qText)
    back.append(name)
    back.append(quote)
        
    inner.append(front)
    inner.append(back)
        
    flip.append(inner)
    html.find("div").append(flip)
    
with open('../templates/' + 'teamcards.html', 'w') as f:
    f.write(str(html.prettify()))

